tap "caskroom/cask"

# Editors
cask "visual-studio-code"
cask "sublime-text"

# Terminal
cask "iterm2"

# Shell
brew "fish"

# Languages
brew "python3"
brew "node"

# Tools
cask "lastpass"
brew "ack"
brew "git-flow"
brew "p7zip"

# Browsers
cask "google-chrome"
cask "firefox"
cask "torbrowser"

